flot/flot

docs/navigate.md, source/jquery.flot.navigate.js, source/jquery.flot.touchNavigate.js, tests/jquery.flot.navigate-interaction.Test.js, tests/jquery.flot.touchNavigate.Test.js
Enables three types of drag/pan interaction behavior: ‘normal’ (tentative naming), smart, and smart-lock.
Add pan mode option to customize the mouse drag interaction behavior.
Add pan touchMode option to customize the touch pan interaction behavior.
This change is moved from engineering-flot PR: https://github.com/ni-kismet/engineering-flot/pull/279.
@andrewdove1, now I need your comments to decide **whether we should change the default behavior and merge two mode options into one**. FYI, the origin default (fixed) behavior is that mouse interaction does smart pan, while touch interaction does 'normal' pan.
=> Add pan mode options to enable/disable smart pan

source/jquery.canvaswrapper.js
What's the problem?
-----------------------
Sometimes the svg container inside the flot-svg div doesn't fit to the parent container 100% on iOS ~~Safari~~(I also see this issue on Chrome, Firefox on iOS). See the picture below
From the pictures we can see that the height of the svg element is 100% but it doesn't fit to its parent container which is the HTML div element with class "flot-svg". 
Why does it happen?
------------------------
I use [remotedebug-ios-webkit-adapter](https://github.com/RemoteDebug/remotedebug-ios-webkit-adapter#usage-with-chrome-canary-and-chrome-devtools) to debug this issue on the iPad. When I pan the graph area, I can see the svg element's height changes. Because the svg element's height is 100% of its parent so I suspect that its parent flot-svg HTMLDIV …
=> fix flot-svg layer display issue on iOS

source/jquery.flot.logaxis.js, tests/jquery.flot.logaxis.Test.js
This issue would only arise when there were multiple axes of a particular orientation and a non-default axis had no data associated with it.
=> Fix for error when changing axis to log when it has no data.

API.md, source/jquery.flot.time.js, tests/jquery.flot.time.Test.js
Added:
- an option to set timeBase as microseconds
- an option to show ticks in sub-second accuracy (millisecond, microsecond)
- timeformat option %s = microseconds, %Ns, in which N is a number denoting accuracy
For example, format string 
- "%H:%M:%S.%s"  would format timestamp 1000500 (microseconds) as "00:00:01.000500"
- "%H:%M:%S.%2s" would format timestamp 1020000 (microseconds) as "00:00:01.02"
=> Added microsecond support to jquery.flot.time.js

source/jquery.flot.drawSeries.js, source/jquery.flot.js, tests/jquery.flot-drawSeries.Test.js
Moved the implementation of the trailing steps to jquery.flot.drawSeries.js (plotLine function) to draw the trailing step without having to create intermediate points that are not present in the original dataset.
Also, added similar modification to the plotLineArea function (for "filled" lines).
=> Removed creation of intermediate datapoints from trailing step algorithm

source/jquery.flot.hover.js
The 'tap' local was being defined after some methods that were using it. This caused errors when using the minified source.
=> Move 'tap' declaration

package-lock.json, package.json
I think files-exist was inadvertently added as a regular dependency and not a dev dependency.
It doesn't look like file-exist is used anywhere, so I'm removing it.
=> Moved files-exist to dev dependency and removed file-exist dependency

source/jquery.flot.hover.js
We were incorrectly removing the event listener on the touch event.
=> Fix memory leak in hover plugin

source/jquery.flot.legend.js
Use `.reduce()` instead of `.map() ` to filter for any series that a user has chosen to exclude from the legend. We must first check to see if the series object has a `label` property, which is done in the ternary operator embedded in the `if` statement on line 283. If it does, the ternary `labelEval` checks for any labelFormatter, and also checks for a falsy `null` value set by the user. If the `label` property doesn't exist, we add a legend entry by default, using the generic `'Plot ' + (i + 1)`
=> fix legend label issue

source/jquery.flot.js, source/jquery.flot.logaxis.js, source/jquery.flot.time.js
For the same reason as in https://github.com/ni-kismet/data-types/pull/45, that `Math.pow` have inconsistent behavior on chrome, flot has test fails.
This PR use the same way to fix it.
=> Use Number coercion to fix the issue that Math.pow() may lose precision

docs/API.md, source/jquery.flot.js
Drawing done is a very useful timing while the user needs some custom side effects, as important as, even more important than, `plotpan` and `plotzoom`. However, flot only triggers the `onDrawingDone`  event on the **event holder**, whose event listener would be clean-up each time the plot is re-created. Is make this event hard to use, since one has to register the listener every time re-create plot. In addition, this event behaves differently than `plotpan` and `plotzoom`. (`plotpan` and `plotzoom` is triggered on place holder instead of event holder)
The PR adds a new event `drawingdone` that is trigger on the place holder. It follows the way of `plotpan` and `plotzoom`. The old event `onDrawingDone` is not changed to prevent breaking.
=> Also trigger 'drawingdone' event to the place holder

gulpfile.js, karma.conf.js, package-lock.json, package.json, source/getCORSCss.js, source/jquery.flot.composeImages.js, source/jquery.flot.fillbetween.js
When we embedded a web-charts in iframe element, if the inner web-charts use a different domain(CORS) css link, then if we need to get this css stylesheet, we will get the error:_Failed to read the 'rules' property from 'CSSStyleSheet'_. This is because the link is [CORS](https://en.wikipedia.org/wiki/Cross-origin_resource_sharing) and we need to set [crossOrigin](https://developer.mozilla.org/en-US/docs/Web/HTML/CORS_enabled_image) attribute to get the css rules.
In jquery.flot.composeImages.js, we use function getCSSRules(document) to get css rules, which will cause issue when the css is from a CORS link.
To allow getting CORS link css rules, we need to set "crossOrigin" attribute. I created a new function:getCrossDomainCSSRules which allow the CORS link to be added correctly.
=> fix css CORS issue

karma.conf.js, package.json, source/getCORSCss.js, tests/corscss.css, tests/getCORSCss.Test.js
Background:
The origin issue is related to this [PR](https://github.com/flot/flot/pull/1651). and this fix is only for solving the same issue on Safari.
Why additional fix on Safari:
1. When CORS link loaded on Safari, the Safari will wrap the cssRule error and return null when we want to get styleSheet.cssRules. which will miss the try catch statement on the [original fix](https://github.com/flot/flot/blob/f33fd255bd53aa99d6f6d7f40ea6da96e8d07f62/source/getCORSCss.js#L69).
2. Seems Safari will load the new link immediately and synchronously if the link's href is same with other loaded link before.
let's pending this change here now until next Monday after another change reviewed.
=> fix cssRule issue on Safari

source/jquery.flot.time.js, tests/jquery.flot.time.Test.js
#1638 
To support microsecond dates, we add methods and properties to regular JS date objects to extend their functionality. However, these extended objects would not behave correctly when using some native date methods (e.g. `SetFullYear()`). We were storing a `microEpoch` value on the date object, which represented the whole date, but that value would not get updated when using any methods that we weren't overriding. 
Instead of keeping track of the whole date value ourselves, I made changes so that the native date object would maintain the millisecond-resolution date value. The microsecond wrapper will now only store the microsecond value.
=> Fix overloading of date types to allow using methods like "setFullYear()"

source/jquery.flot.js
An index of 0 is falsey and fails this check
=> Explicity perform null check on bar hover index

source/jquery.flot.js, tests/jquery.flot.Test.js
When we set up the initial state of flot, then if we have no data we should honor the given min and max supplied for an axis, even if its autoscale setting is set to 'loose'.
=> Update snap range to ticks behavior

source/jquery.flot.drawSeries.js, tests/jquery.flot-drawSeries.Test.js
If we have NaNs present in our data when drawing lines we should be moving the pen to the next valid data point and pick up drawing there.
=> Skip NaNs when drawing lines

source/jquery.flot.hover.js
Fixes issue #1676
jquery.flot.hover.js was holding onto a global plot variable, so if you had multiple plots on the same page whichever one called init last would process all of the hover events. I moved all of the functionality to be nested in order to capture each plot independently. This is similar to how other plugins work, like jquery.flot.navigate.js.
=> Refactor hover plugin to not use global plot

source/jquery.flot.hover.js
Because of the refactoring done in https://github.com/flot/flot/pull/1683, the 'tap' object was being used before it was defined in the hover init code. This doesn't actually cause problems when using the source, but the minified/transpiled distribution was broken. This has been a problem before (https://github.com/flot/flot/pull/1631) so I turned the tap object into a function. 
I tested hovering on some examples using the minified source and everything works.
=> Fix broken distribution for jquery.flot.hover.js

source/jquery.flot.js
If the second data point of a bar graph was null, the initial minDistance calculation for 'computeBarWidth' would be incorrect and could break the axis scaling for the whole graph. Because null is coerced to 0 in javascript arithmetic, 
`distance = series.datapoints.points[pointsize] - series.datapoints.points[0]` 
would return a negative number if `series.datapoints.points[pointsize]` was null. Since we're looping through all of the points to the find the min distance, that calculation was unnecessary anyway. I just added a simple check to return the default bar width if there's only 1 or 0 data points.
=> Remove initial min distance calculation between first two points

source/jquery.flot.hover.js, tests/jquery.flot.hover.Test.js
Reset happened in processRawData but there each axis is listed as used = false. This can cause a crash if setData is called because pos.x and pos.y are undefined (this happened when I modified the interacting example to update on a timer). Instead do the reset in processDatapoints where axis.used = true
=> Move when reset happens

source/jquery.flot.time.js, tests/jquery.flot.time.Test.js
In issue #1707, @skortchmark9 pointed out that we are double-counting millisecond values on microsecond date objects. When the date is set, we pass the epoch (including milliseconds) to the base Date `setTime` method, and then we would also keep the millisecond value in the `microseconds` field. I changed the implementation so that now the `microseconds` field only stores the microseconds value (which I meant to be the case in #1660, but missed an aspect of it).
=> Fixed issue with inconsistent millisecond values on microsecond dates

source/jquery.flot.drawSeries.js, source/jquery.flot.js, tests/jquery.flot.hover.Test.js
This fix is primarily relevant for stacked bar charts. In the current version of flot, if you try to hover on stacked bars, you will only receive hover events for the last series in the data. This is because `findNearbyBar` doesn't take into account series with a point size of 3 (where the 3rd point is the bottom of the bar). I used the same pattern from `drawSeriesBars` to fix this. I also renamed a variable in both places to be closer to its actual meaning.
=> Fix bar hovering for charts with bottom points specified 

source/jquery.flot.pie.js
If the last mousemove event on a pie chart is over a slice, it will get stuck in the highlight state. We need to trigger a hover event when the mouse leaves the placeholder element so that highlights get cleared. 
This is especially a problem when the radius of a pie chart is 1, such that there is no gap between the edges of slices and the container element:
=> Clear pie chart hover highlights on mouseleave

examples/selection/index.html
After the changes made in d1fef617, selection will not work unless the `jquery.event.drag.js` library is included.
=> Update the selection example.

examples/interacting/index.html
Since jQuery fadeIn is used there is a delay before the tooltip shows up in which time the user may still be moving the mouse.   It is possible to have tooltip show up after user has already removed cursor from canvas.  See:  https://stackoverflow.com/a/29588856/562644
=> Cancel jQuery animation queue on hover off

package-lock.json, source/jquery.flot.navigate.js
The navigate plugin for 0.8.3 had the options for panRange and zoomRange that would limit how far you could scroll or zoom. This branch returns the feature to the plugin. This also works for the touch plugins, as they ultimately call functions within the navigate plugin.
=> Pan and zoom limits

source/jquery.canvaswrapper.js, tests/jquery.flot.canvaswrapper.Test.js
I noticed when testing multi-line axis names that flot doesn't render SVG text with more than 2 lines correctly. After the second line, the lines are spaced out farther than expected.
It looks like we're incorrectly configuring the line spacing in `addTspanElements()` in jquery.canvaswrapper.js. We set the `dy` attribute in each `tspan` element (each of which holds a line of text) to move the text down the page. `dy` moves the `tspan` relative to the previous text - in this case, the previous `tspan`. We were setting `dy` to the index of the line, which would move each line progressively further away from the previous line. I changed it so that we always move each subsequent line only `1em` from the previous line.
=> Fixed multi line SVG text spacing

source/jquery.flot.js, tests/jquery.flot.Test.js
=> Don't show y-axis endpoints for horizontal bar charts

source/jquery.flot.js, source/jquery.flot.stack.js, tests/jquery.flot.Test.js
Fixes issues like this where the axis of a horizontal bar chart is squished:
We can't assume that the 3rd coordinate (used to specify the bottom of a filled area/bar) will always be for a Y Axis, because if you're using horizontal bars, then the X and Y data should be transposed. Without this change, `computeRangeForDataSeries` was using the 3rd coordinate of a datapoints set as part of the min/max calculation for the wrong axis.
=> 3rd coordinate should swap axes when bars are horizontal

source/jquery.flot.js
Issue:  ticks: 0 - 0.25 - 0.5 - 0.75 - 1 will be incorrectly rounded to 0 - 0.3 - 0.5 - 0.8 - 1
This is visible in the examples: http://www.flotcharts.org/flot/examples/axes-tickLabels/index.html
In the image above the horizontal ticks should be 10017.00 - 10017.25 - x.50 - x.75 etc. 
This is caused by a null reference to `axis.tickDecimals`. When this is `null` the extra decimal for `tickRange` 2.5 is not added.
=> Fix precission when tickSize = 2.5 (fix null reference)

source/jquery.flot.time.js, tests/jquery.flot.time.Test.js
This PR addresses two already-reported issues when using micro epoch with the time axis
The code that resets the time of the first tick does not takes into account the seconds/millis/micro steps:
This PR adds the following sections to reset the micro and millis when needed:
```javascript
if (step >= timeUnitSize.millisecond) {
d.setMicroseconds(0);
}
if (step >= timeUnitSize.second) {
d.setMilliseconds(0);
}
```
The result after the fix:
This also fixes another issue mentioned here:
https://github.com/flot/flot/issues/1743
Mentioned here:
https://github.com/flot/flot/issues/1792
In some cases, the date tick generator will run in an infinite loop due to a bug in the custom micro date implementation provided by Flot time plugin. 
In short: The micro epoch is rounded to 3 decimals AFTER …
=> Fix time plugin not to skip ticks & Avoid infinite loop when using microsecond min tick size
